---
# tasks file for docker | Debian

- name: Debian | Installing {{ docker_debian_pre_reqs }}
  become: true
  apt:
    name: "{{ docker_debian_pre_reqs }}"
    state: "{{ docker_debian_pre_reqs_desired_state }}"
    force_apt_get: yes
    update_cache: yes

- name: Debian | Ensure docker gpg key exists.
  become: true
  apt_key:
    url: "{{ docker_repo_gpg_key }}"
    state: "{{ docker_repo_debian_desired_state }}"

- name: Debian | Adding docker repository.
  become: true
  apt_repository:
    repo: "{{ docker_repo_debian }}"
    state: "{{ docker_repo_debian_desired_state }}"
    filename: "{{ docker_repo_debian_filename }}"
    codename: "{{ ansible_lsb['codename'] }}"
    update_cache: yes

- name: Debian | Installing {{ docker_apps }}
  become: true
  apt:
    name: "{{ docker_apps }}"
    state: "{{ docker_apps_desired_state }}"
    force_apt_get: yes
  notify:
    - "set_{{ docker_service_name }}_service_state"
    - "set_{{ docker_service_name }}_service_boot_state"
    
- name: Permitting Apache to run docker commands
  lineinfile:
    dest: /etc/sudoers.d/apache-docker
    line: 'www-data ALL=NOPASSWD: /usr/bin/docker'
    create: yes
    owner: root 
    group: root 
    mode: "0440"
    state: present
    validate: 'visudo -c -f %s'
    
- name: Removing index.html from /var/www/html/
  file:
    path: /var/www/html/index.html
    state: absent
    
- name: Building Docker Web
  git:
    repo: https://github.com/Cyb3rG0dzilla/Docker-Web.git
    dest: /var/www/html/
    clone: yes
    update: yes
